[versions]
ktor = "2.3.12"
kord-cache = "0.5.4"

[libraries]
kotlinx-serialization-json-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-io", version = "1.7.2" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-resources = { group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }

stdx-envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "1.3.0" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.0" }

kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version = "0.5.1" }

java-jwt = { group = "com.auth0", name = "java-jwt", version = "4.4.0" }
java-jwks = { group = "com.auth0", name = "jwks-rsa", version = "0.22.1" }

kord-cache-api = { group = "dev.kord.cache", name = "cache-api", version.ref = "kord-cache" }
kord-cache-map = { group = "dev.kord.cache", name = "cache-map", version.ref = "kord-cache" }
kord-cache-redis = { group = "dev.kord.cache", name = "cache-redis", version.ref = "kord-cache" }
