[versions]
ktor = "2.3.12"

[libraries]
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-resources = { group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }

stdx-envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "1.3.0" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.0" }


[plugins]
graalvm = { id = "org.graalvm.buildtools.native", version = "0.10.2" }
