[versions]
ktor = "3.0.3"
kord-cache = "0.5.6"
kotlin = "2.1.0"
coroutines = "1.10.1"
bouncycastle = "1.79"

[libraries]
kotlinx-serialization-json-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-io", version = "1.8.0-RC" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-resources = { group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }

stdx-envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "1.3.0" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.3" }

kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version = "0.6.0" }

java-jwt = { group = "com.auth0", name = "java-jwt", version = "4.4.0" }
java-jwks = { group = "com.auth0", name = "jwks-rsa", version = "0.22.1" }
nimbus-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version = "9.48" }
bouncycastle-bcpkix-jdk18on = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }

doh = { group = "tech.relaycorp", name = "doh", version = "1.0.69" }

kord-cache-api = { group = "dev.kord.cache", name = "cache-api", version.ref = "kord-cache" }
kord-cache-map = { group = "dev.kord.cache", name = "cache-map", version.ref = "kord-cache" }
kord-cache-redis = { group = "dev.kord.cache", name = "cache-redis", version.ref = "kord-cache" }

kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.11.4" }
